"""Tests for the firmware signing module and its compatibility with the server."""

import sys
from pathlib import Path

import pytest

from swelter import ingest_server


@pytest.fixture
def fw_signing() -> object:
    """Import the firmware signing module."""
    firmware_path = Path(__file__).resolve().parent.parent / "firmware" / "src"
    if str(firmware_path) not in sys.path:
        sys.path.insert(0, str(firmware_path))
    import signing as fw_signing

    yield fw_signing
    # Clean up
    if str(firmware_path) in sys.path:
        sys.path.remove(str(firmware_path))


class TestFirmwareSigningModule:
    """Test the firmware signing.py module."""

    def test_firmware_module_exists(self) -> None:
        """The firmware signing.py module can be imported."""
        firmware_path = Path(__file__).resolve().parent.parent / "firmware" / "src"
        assert (firmware_path / "signing.py").is_file()

    def test_firmware_signing_function_exists(self, fw_signing: object) -> None:
        """The firmware module has the sign function."""
        assert hasattr(fw_signing, "sign")
        assert callable(fw_signing.sign)

    def test_firmware_headers_function_exists(self, fw_signing: object) -> None:
        """The firmware module has the headers function."""
        assert hasattr(fw_signing, "headers")
        assert callable(fw_signing.headers)

    def test_firmware_utc_timestamp_function(self, fw_signing: object) -> None:
        """The firmware module can generate UTC timestamps."""
        assert hasattr(fw_signing, "utc_timestamp")
        ts = fw_signing.utc_timestamp()
        # Should be ISO-8601 format YYYY-MM-DDTHH:MM:SSZ
        assert len(ts) == 20
        assert ts.endswith("Z")
        assert "T" in ts

    def test_firmware_signature_consistency(self, fw_signing: object) -> None:
        """Firmware signing produces consistent signatures."""
        key_hex = "0123456789abcdef" * 4
        node_id = "node-1"
        timestamp = "2026-07-01T12:00:00Z"
        body = b'{"readings": {"pm25_ugm3": 23.5}}'

        sig1 = fw_signing.sign(key_hex, node_id, timestamp, body)
        sig2 = fw_signing.sign(key_hex, node_id, timestamp, body)

        assert sig1 == sig2
        assert len(sig1) == 64  # SHA-256 as hex


class TestServerFirmwareCompatibility:
    """Test that server and firmware signing produce identical signatures."""

    def test_signing_compatibility(self, fw_signing: object) -> None:
        """Server and firmware signatures are identical."""
        key_hex = "0123456789abcdef" * 4
        node_id = "test-node"
        timestamp = "2026-07-01T12:00:00Z"
        body = b'{"node_id": "test-node", "readings": {"pm25_ugm3": 42}}'

        fw_sig = fw_signing.sign(key_hex, node_id, timestamp, body)
        key_bytes = bytes.fromhex(key_hex)
        server_sig = ingest_server.sign(key_bytes, node_id, timestamp, body)

        assert fw_sig == server_sig

    def test_headers_contain_valid_signature(self, fw_signing: object) -> None:
        """Headers generated by firmware contain a valid signature."""
        key_hex = "0123456789abcdef" * 4
        node_id = "test-node"
        body = b'{"node_id": "test-node", "readings": {"temperature_c": 25}}'

        # Generate headers with a fixed timestamp for reproducibility
        fixed_ts = "2026-07-01T12:00:00Z"
        headers = fw_signing.headers(key_hex, node_id, body, timestamp=fixed_ts)

        # Verify the signature is valid on the server side
        key_bytes = bytes.fromhex(key_hex)
        server_sig = ingest_server.sign(key_bytes, node_id, fixed_ts, body)

        assert headers[fw_signing.SIGNATURE_HEADER] == server_sig

    def test_canonical_message_match(self, fw_signing: object) -> None:
        """Firmware and server produce the same canonical message."""
        node_id = "my-node"
        timestamp = "2026-07-02T14:30:00Z"
        body = b"raw sensor data"

        # Server side
        server_msg = ingest_server.canonical_message(node_id, timestamp, body)

        # Firmware side (the message format is documented in signing.py)
        import hashlib

        body_digest = hashlib.sha256(body).hexdigest()
        fw_msg = f"{node_id}\n{timestamp}\n{body_digest}".encode()

        assert server_msg == fw_msg

    def test_various_body_formats(self, fw_signing: object) -> None:
        """Signatures work with various payload formats."""
        key_hex = "abcdef0123456789" * 4
        node_id = "sensor-5"
        timestamp = "2026-07-03T08:15:00Z"

        # Test with dict-like JSON
        body_dict = b'{"readings": {"temp_c": 22.5, "humidity_pct": 65}}'
        fw_sig_dict = fw_signing.sign(key_hex, node_id, timestamp, body_dict)
        server_key = bytes.fromhex(key_hex)
        server_sig_dict = ingest_server.sign(server_key, node_id, timestamp, body_dict)
        assert fw_sig_dict == server_sig_dict

        # Test with array format
        body_array = b'[{"timestamp": "2026-07-03T08:00:00Z", "pm25_ugm3": 15}]'
        fw_sig_array = fw_signing.sign(key_hex, node_id, timestamp, body_array)
        server_sig_array = ingest_server.sign(server_key, node_id, timestamp, body_array)
        assert fw_sig_array == server_sig_array

    def test_key_rotation_scenario(self, fw_signing: object) -> None:
        """Test that old and new keys produce different signatures."""
        old_key_hex = "0123456789abcdef" * 4
        new_key_hex = "fedcba9876543210" * 4
        node_id = "node-with-rotated-key"
        timestamp = "2026-07-04T10:00:00Z"
        body = b'{"readings": {"pm25_ugm3": 18}}'

        old_sig = fw_signing.sign(old_key_hex, node_id, timestamp, body)
        new_sig = fw_signing.sign(new_key_hex, node_id, timestamp, body)

        assert old_sig != new_sig
        # Both should still be valid hex signatures
        assert len(old_sig) == 64
        assert len(new_sig) == 64
