"""The ``swelter`` command line: ingest, qc, calibrate, aggregate, export, serve, demo, rebuild —
plus the operator-side write path (ingest-serve, node-key) and the host-facing preview
(node-preview).

This is the one-command surface a neighbourhood collective actually touches. Every subcommand
is a thin wrapper over the library functions, so anything the CLI does is equally scriptable
and testable. ``swelter demo`` is the keystone: it replays the recorded week in ``data/demo``
through the whole pipeline — ingest → calibrate → aggregate → export — and optionally serves
the dashboard, with no hardware in the loop.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any, cast

import yaml

from . import (
    __version__,
    aggregate,
    alerts,
    calibrate,
    cards,
    cooling_centers,
    crosswalk,
    export,
    ingest,
    ingest_server,
    integrity,
    obs,
    qc,
    snapshot,
)
from .config import (
    NetworkConfig,
    NodeConfig,
    config_concerns,
    consent_concerns,
    haversine_m,
    label_concerns,
    load_config,
    load_config_doc,
)
from .models import RAW, Observation
from .server import ServerContext, serve
from .store import SqliteStore, open_store, store_paths

DEFAULT_STORE = "store"
DEFAULT_CONFIG = "network.yaml"
DEFAULT_WEB = "web"
DEFAULT_DATA = "data/demo"
DEFAULT_COOLING = "data/cooling_centers.geojson"
DEFAULT_INTERVAL_S = 3600.0
DEFAULT_KEYS = "node-keys.yaml"  # operator-local; outside network.yaml and the copyable store

#: A minimal, commented starter network written by `swelter init`. __NAME__ is replaced with a
#: YAML-safe quoted name. Two nodes, one reference monitor, one co-location window — the smallest
#: thing that runs end to end, ready to edit. The full guide is docs/ADD-YOUR-NEIGHBORHOOD.md.
STARTER_NETWORK = """\
# swelter network — generated by `swelter init`. Edit it to describe your own network.
# Guide: docs/ADD-YOUR-NEIGHBORHOOD.md. Privacy: every coordinate snaps to a grid_resolution_m cell
# unless a host opts a node into `location: precise` — a collective decision (docs/governance.md).

name: __NAME__
grid_resolution_m: 150          # published cell size in metres (~a block); a collective decision
languages:
- en
- es

reference_monitors:             # the trusted station(s) you co-locate against to earn calibration
- monitor_id: ref-aqs-0001
  label: Regulatory AQS station (your city)
  source: US EPA AQS site XX-XXX-XXXX

nodes:                          # one entry per sensor location; node_id is the ONLY identifier
- node_id: node-01
  label: Cedar & 4th            # a place-name residents say out loud
  lat: 38.575057                # any coordinate inside the cell; published coarse unless `precise`
  lon: -121.509361
  location: coarse
- node_id: node-02
  label: Oak & 4th
  lat: 38.575120
  lon: -121.506400
  location: coarse

calibration_windows:            # one per (node, parameter); a node with none stays raw/provisional
- node_id: node-01
  reference: ref-aqs-0001
  parameter: pm25_ugm3
  start: '2026-06-01T00:00:00Z'
  end: '2026-06-03T23:00:00Z'
"""


def _err(message: str) -> None:
    print(message, file=sys.stderr)


def _corrections_skipped_stale(
    raw: list[Observation],
    registry: calibrate.CorrectionRegistry,
    calibrated: list[Observation],
) -> int:
    """Raw readings that had a registered correction available but were left raw.

    Mirrors ``calibrate.apply()``'s own "leave it raw" branch (a correction is registered for
    the node/parameter but its required co-timed predictor — e.g. humidity — was not present
    on that reading) without duplicating that logic: it diffs the set of ``(node, ts,
    parameter)`` keys that *could* have been corrected against the set that actually were.
    """
    candidates = {
        (o.node_id, o.timestamp, o.parameter)
        for o in raw
        if registry.get(o.node_id, o.parameter) is not None
    }
    applied = {(o.node_id, o.timestamp, o.parameter) for o in calibrated}
    return len(candidates - applied)


def _print_concerns(errors: list[str], warnings: list[str]) -> None:
    for message in errors:
        _err(f"swelter: ✗ {message}")
    for message in warnings:
        _err(f"swelter: ⚠ {message}")


def _load_config(path: str) -> NetworkConfig:
    if Path(path).is_file():
        config, doc = load_config_doc(path)
        errors, warnings = config_concerns(config, doc)
        _print_concerns(errors, warnings)
        for concern in label_concerns(config):
            _err(f"swelter: ⚠ {concern}")
        for concern in consent_concerns(config):
            _err(f"swelter: ⚠ {concern}")
        return config
    _err(f"swelter: config {path} not found; using an empty network")
    return NetworkConfig()


def _node_models(config: NetworkConfig) -> dict[str, str]:
    """node_id → sensor_model, for every node that registered one.

    Feeds `calibrate.fit`'s (parameter, model) family lookup. Nodes without a `sensor_model` are
    omitted, so `fit` falls back to the per-parameter default for them exactly as before
    model-awareness existed.
    """
    return {node.node_id: node.sensor_model for node in config.nodes if node.sensor_model}


# -- subcommands -------------------------------------------------------------


def cmd_ingest(args: argparse.Namespace) -> int:
    if not Path(args.input).is_file():
        _err(f"swelter: input {args.input} not found")
        return 1
    paths = store_paths(args.store)
    manifest = obs.RunManifest()
    with open_store(args.store) as store:
        result = ingest.ingest_file(args.input, store, quarantine_path=paths["quarantine"])
    manifest.record(
        "ingest",
        "payloads ingested",
        payloads_accepted=result.accepted_payloads,
        payloads_quarantined=result.quarantined,
    )
    manifest.finish()
    obs.write_manifest(paths["dir"], manifest)
    _err(
        f"swelter: ingested {result.accepted_payloads} payloads → "
        f"{result.observations_written} new observations "
        f"({result.duplicates} duplicates, {result.quarantined} quarantined)"
    )
    return 0


def cmd_qc(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    with open_store(args.store) as store:
        raw = store.read(calibration=RAW)
        all_obs = list(store.all())
    if not raw:
        _err("swelter: store is empty")
        return 0
    latest = max(o.timestamp for o in raw)
    gaps = qc.detect_gaps(raw, args.interval)
    health = qc.node_health(
        raw, latest, offline_after_s=args.interval * 3, expected_interval_s=args.interval
    )
    # Coverage-equity: calibrated-vs-raw node counts per published cell, so an under-calibrated
    # block is visible rather than hidden behind the network average (audit B3). Descriptive
    # coverage, not a ranking of neighborhoods (see qc.coverage_equity / docs/RESEARCH-ROADMAP).
    coverage = qc.coverage_equity(all_obs, aggregate.node_cell_map(config))
    cov = cast(dict[str, Any], coverage["summary"])
    if args.json:
        payload = {
            "nodes": [
                {
                    "node_id": n.node_id,
                    "status": n.status,
                    "observations": n.observations,
                    "completeness": n.completeness,
                    "flagged_fraction": round(n.flagged_fraction, 3),
                    "online": n.online,
                    "last_seen": n.last_seen,
                }
                for n in health
            ],
            "gaps": [
                {
                    "node_id": g.node_id,
                    "parameter": g.parameter,
                    "start": g.start,
                    "end": g.end,
                    "minutes": round(g.seconds / 60),
                }
                for g in gaps
            ],
            "coverage_equity": coverage,
        }
        print(json.dumps(payload, indent=2))
        return 0
    not_ok = sum(1 for n in health if n.status != "ok")
    _err(
        f"swelter: {len(health)} nodes ({not_ok} degraded/offline), {len(gaps)} gaps "
        f"over interval {int(args.interval)}s"
    )
    for gap in gaps[:10]:
        _err(
            f"  gap  {gap.node_id}/{gap.parameter}  {gap.start} → {gap.end}  "
            f"({round(gap.seconds / 60)} min)"
        )
    for node in health:
        _err(
            f"  {node.node_id:>10}  {node.status.upper():<8}  {node.observations:>6} obs  "
            f"{node.completeness * 100:5.1f}% complete  {node.flagged_fraction * 100:5.1f}% flagged"
        )
    _err(
        f"swelter: coverage — {cov['calibrated_nodes']}/{cov['nodes']} nodes calibrated, "
        f"{cov['confirmed_cells']}/{cov['cells']} cells confirmed, "
        f"{cov['provisional_cells']} provisional cell(s)"
    )
    for cell in cast(list[dict[str, Any]], coverage["cells"]):
        if not cell["confirmed"]:
            name = cell["label"] or cell["cell_id"]
            _err(
                f"  provisional cell  {name}  "
                f"({cell['calibrated_nodes']}/{cell['nodes']} calibrated)"
            )
    return 0


def cmd_calibrate(args: argparse.Namespace) -> int:
    if not Path(args.colocation).is_file():
        _err(f"swelter: colocation {args.colocation} not found")
        return 1
    config = _load_config(args.config)
    pairs = calibrate.read_colocation(args.colocation)
    registry = calibrate.fit(pairs, models=_node_models(config))
    paths = store_paths(args.store)
    registry.to_yaml(paths["registry"])
    _err(f"swelter: fit {len(registry)} corrections → {paths['registry']}")
    for c in registry.all():
        _err(f"  {c.version:<28} n={c.n:<4} R²={c.r2:.3f}  ±{c.residual_std} {c.parameter}")
    manifest = obs.RunManifest()
    if not args.fit_only:
        with open_store(args.store) as store:
            raw = store.read(calibration=RAW)
            store.drop_calibrated()
            calibrated = [o for o in calibrate.apply(raw, registry) if o.calibration != RAW]
            written = store.write(calibrated)
        manifest.record(
            "calibrate",
            "corrections applied",
            corrections_applied=written.written,
            corrections_skipped_stale=_corrections_skipped_stale(raw, registry, calibrated),
        )
        _err(f"swelter: applied corrections → {written.written} calibrated observations")
    manifest.finish()
    obs.write_manifest(paths["dir"], manifest)
    return 0


def cmd_aggregate(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    paths = store_paths(args.store)
    with open_store(args.store) as store:
        surface = aggregate.aggregate(store.all(), config)
    out = Path(args.out or paths["aggregate"])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(surface.snapshot_geojson(), indent=2), encoding="utf-8")
    manifest = obs.RunManifest()
    manifest.record(
        "aggregate",
        "surface built",
        cells_built=len(surface.cells),
        cells_provisional=sum(1 for c in surface.cells if c.provisional),
    )
    manifest.finish()
    obs.write_manifest(paths["dir"], manifest)
    _err(f"swelter: {len(surface.cells)} cell-hours → {out}")
    return 0


def cmd_alerts(args: argparse.Namespace) -> int:
    """Build the neighborhood heat/AQI alerts feed (JSON + Atom) from the current surface."""
    config = _load_config(args.config)
    with open_store(args.store) as store:
        surface = aggregate.aggregate(store.all(), config)
    feed = alerts.build_feed(
        surface,
        network=config.name,
        base_url=args.base_url,
        thresholds=config.alert_thresholds or None,
    )
    if args.format == "atom":
        sys.stdout.write(feed.to_atom())
    elif args.format == "json":
        sys.stdout.write(json.dumps(feed.to_json(), indent=2) + "\n")
    if args.web:
        _write_web_alerts(Path(args.web), surface, config)
        _err(f"swelter: wrote alerts.json + alerts.xml → {args.web}/")
    _err(f"swelter: {len(feed.alerts)} active alert(s) at {feed.bucket or 'no data'}")
    return 0


def cmd_cards(args: argparse.Namespace) -> int:
    """Emit print-CSS bilingual neighborhood cards — one door flyer / fridge card per published
    cell, from the same surface + cooling-center + i18n data the dashboard and alerts feed use
    (EXP-11). The paper channel for residents a screen or a connection doesn't reach."""
    config = _load_config(args.config)
    with open_store(args.store) as store:
        surface = aggregate.aggregate(store.all(), config)
    cooling_path = _cooling_path(args.cooling_centers)
    dataset = cooling_centers.load(cooling_path) if cooling_path else cooling_centers.empty()
    html = cards.render_cards(
        surface,
        dataset,
        lang=args.lang,
        area=args.area or None,
        large_type=args.large_type,
        feed_url=args.feed_url,
    )
    if args.out and args.out != "-":
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(html, encoding="utf-8")
        _err(f"swelter: wrote {len(surface.latest_by_cell())} card(s) → {out}")
    else:
        sys.stdout.write(html)
    return 0


def cmd_export(args: argparse.Namespace) -> int:
    with open_store(args.store) as store:
        observations = store.read(
            parameter=args.parameter, node_id=args.node, since=args.since, until=args.until
        )
        raw = store.read(calibration=RAW)
    gaps = qc.detect_gaps(raw, args.interval)
    if args.format == "json":
        sys.stdout.write(
            export.to_json(
                observations, indent=2, license=args.license, attribution=args.attribution
            )
        )
    else:
        sys.stdout.write(
            export.to_csv(observations, license=args.license, attribution=args.attribution)
        )
    _err(export.summarize(observations, gaps=gaps, license=args.license))
    return 0


def _cooling_path(path: str) -> Path | None:
    """The cooling-center dataset path if it exists, else ``None`` (overlay simply stays empty)."""
    p = Path(path)
    return p if p.is_file() else None


def cmd_serve(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    store = open_store(args.store)
    base = f"http://{args.host}:{args.port}"
    ctx = ServerContext(
        store=store,
        config=config,
        web_dir=Path(args.web),
        base_url=base,
        cooling_centers_path=_cooling_path(args.cooling_centers),
        store_dir=store_paths(args.store)["dir"],
    )
    _err(f"swelter: serving dashboard + API at {base}  (Ctrl-C to stop)")
    _err(f"  dashboard {base}/   ·   SensorThings {base}/v1.1   ·   export {base}/export.csv")
    try:
        serve(ctx, host=args.host, port=args.port)
    finally:
        store.close()
    return 0


def cmd_ingest_serve(args: argparse.Namespace) -> int:
    """Run the authenticated node write path: a write-only listener, per-node HMAC keys.

    Kept out of ``swelter serve`` on purpose — the public read surface and the node write
    surface are different trust boundaries and stay in different processes.
    """
    keys_path = Path(args.keys)
    if not keys_path.is_file():
        _err(f"swelter: keys file {args.keys} not found")
        _err(f"  issue one key per node first:  swelter node-key <node_id> --keys {args.keys}")
        return 1
    try:
        keys = ingest_server.load_keys(keys_path)
    except ingest_server.KeyfileError as exc:
        _err(f"swelter: {exc}")
        return 1
    if not keys:
        _err(f"swelter: keys file {args.keys} holds no node keys; issue them with swelter node-key")
        return 1
    paths = store_paths(args.store)
    store = open_store(args.store)
    ctx = ingest_server.IngestServerContext(
        store=store,
        keys=keys,
        quarantine_path=paths["quarantine"],
        skew_s=args.skew,
    )
    base = f"http://{args.host}:{args.port}"
    route = ingest_server.INGEST_ROUTE
    _err(f"swelter: ingest listener (write-only, per-node HMAC) at {base}{route}")
    _err(
        f"  {len(keys)} node key(s) from {args.keys} · replay window ±{int(args.skew)}s · "
        f"auth failures → {paths['quarantine']}  (Ctrl-C to stop)"
    )
    try:
        ingest_server.serve(ctx, host=args.host, port=args.port)
    finally:
        store.close()
    return 0


def cmd_node_key(args: argparse.Namespace) -> int:
    """Issue (or rotate) a node's ingest key into the operator-local keys file.

    Prints the key to stdout — the one moment it is visible — for the operator to copy into the
    node's uncommitted ``config.py``. Who gets a key, and when one is rotated or revoked, is a
    collective decision (docs/governance.md); this command is just the mechanism.
    """
    try:
        key = ingest_server.issue_key(Path(args.keys), args.node_id)
    except ingest_server.KeyfileError as exc:
        _err(f"swelter: {exc}")
        return 1
    _err(f"swelter: issued ingest key for {args.node_id} → {args.keys} (owner-only, mode 0600)")
    _err("  copy the key below into the node's uncommitted config.py as `ingest_key`.")
    _err("  never commit it, never put it in network.yaml, never publish the keys file;")
    _err("  re-running this command for the same node rotates (replaces) the key.")
    print(key)
    return 0


def _print_node_preview(node: NodeConfig, config: NetworkConfig) -> None:
    """Print what the map/API publishes for one node, versus its private exact coordinate."""
    label = f" ({node.label})" if node.label else ""
    print(f"node {node.node_id}{label}")
    if node.lat is None or node.lon is None:
        print("  not placed — publishes nothing (no location on record)")
        print()
        return
    print(f"  your private coordinate — never published: {node.lat:.6f}, {node.lon:.6f}")
    published = node.public_location(config.grid_resolution_m)
    assert published is not None  # noqa: S101 (lat/lon set, so this cannot be None)
    cell_id, cell_label = aggregate.node_cell_map(config).get(node.node_id, ("", ""))
    label_suffix = f" ({cell_label})" if cell_label else ""
    print(f"  published coordinate: {published[0]:.6f}, {published[1]:.6f}")
    print(f"  published cell: {cell_id}{label_suffix}")
    offset_m = haversine_m(node.lat, node.lon, published[0], published[1])
    print(f"  map shows a point ~{offset_m:.0f} m from your sensor")
    print(f"  location mode: {node.location}")
    if node.location == "precise":
        print(
            "  ⚠ WARNING: location is 'precise' — your EXACT coordinate is published as-is. "
            "Coarse-by-default grid-snap protection is OFF for this node. Switch `location` "
            "back to 'coarse' in network.yaml to publish only the grid cell."
        )
    print()


def cmd_node_preview(args: argparse.Namespace) -> int:
    """Show a host exactly what the map/API publishes for their node(s).

    Read-only and host-facing: it never changes a node's location or its published mode, it
    just makes visible — in the host's own terminal — the same coordinate the map and API
    already publish, so "coarse by default" is a fact a host can verify, not just a promise.
    """
    config = _load_config(args.config)
    if args.node_id:
        node = config.node(args.node_id)
        if node is None:
            _err(f"swelter: node {args.node_id} not found in {args.config}")
            return 1
        _print_node_preview(node, config)
        return 0
    if not config.nodes:
        _err(f"swelter: no nodes registered in {args.config}")
        return 0
    for node in config.nodes:
        _print_node_preview(node, config)
    return 0


def cmd_demo(args: argparse.Namespace) -> int:
    data = Path(args.data)
    config = _load_config(args.config)
    paths = store_paths(args.store)
    paths["db"].unlink(missing_ok=True)  # a fresh demo store every run; replay is idempotent
    manifest = obs.RunManifest()

    with SqliteStore(paths["db"]) as store:
        result = ingest.ingest_file(
            data / "observations.jsonl", store, quarantine_path=paths["quarantine"]
        )
        manifest.record(
            "ingest",
            "demo replay ingested",
            payloads_accepted=result.accepted_payloads,
            payloads_quarantined=result.quarantined,
        )
        _err(f"swelter demo: replayed {result.observations_seen} observations from recorded data")

        colocation = data / "colocation.jsonl"
        if colocation.is_file():
            registry = calibrate.fit(
                calibrate.read_colocation(colocation), models=_node_models(config)
            )
            registry.to_yaml(paths["registry"])
            raw = store.read(calibration=RAW)
            calibrated = [o for o in calibrate.apply(raw, registry) if o.calibration != RAW]
            store.write(calibrated)
            manifest.record(
                "calibrate",
                "demo replay calibrated",
                corrections_applied=len(calibrated),
                corrections_skipped_stale=_corrections_skipped_stale(raw, registry, calibrated),
            )
            _err(
                f"swelter demo: fit {len(registry)} corrections, wrote {len(calibrated)} calibrated"
            )

        surface = aggregate.aggregate(store.all(), config)
        manifest.record(
            "aggregate",
            "demo replay surface built",
            cells_built=len(surface.cells),
            cells_provisional=sum(1 for c in surface.cells if c.provisional),
        )
        paths["aggregate"].write_text(
            json.dumps(surface.snapshot_geojson(), indent=2), encoding="utf-8"
        )
        _write_web_sample(
            Path(args.web),
            surface,
            attribution="Synthetic demonstration data — no real sensors (gen_demo_data.py).",
        )
        _coverage = qc.coverage_equity(store.all(), aggregate.node_cell_map(config))
        _write_web_health(
            Path(args.web),
            store.read(calibration=RAW),
            args.interval,
            coverage=_coverage,
            store_dir=args.store,
        )
        _write_web_alerts(Path(args.web), surface, config)
        _write_web_cooling_centers(Path(args.web), Path(args.cooling_centers))
        all_obs = list(store.all())
        gaps = qc.detect_gaps(store.read(calibration=RAW), args.interval)
        _err(export.summarize(all_obs, gaps=gaps))

    manifest.finish()
    obs.write_manifest(paths["dir"], manifest)

    if args.serve:
        store = open_store(args.store)
        base = f"http://{args.host}:{args.port}"
        ctx = ServerContext(
            store=store,
            config=config,
            web_dir=Path(args.web),
            base_url=base,
            cooling_centers_path=_cooling_path(args.cooling_centers),
            store_dir=paths["dir"],
        )
        _err(f"swelter demo: serving at {base}  (Ctrl-C to stop)")
        try:
            serve(ctx, host=args.host, port=args.port)
        finally:
            store.close()
    return 0


def _write_web_sample(
    web_dir: Path, surface: aggregate.Surface, *, attribution: str = "", max_cells: int = 4000
) -> None:
    """Refresh the dashboard's offline fallback if web/ exists, capped to keep the static payload
    light on a host like GitHub Pages — the most recent hourly buckets up to ~``max_cells`` cells,
    so a large network does not bloat the committed sample (the live API has the full history)."""
    if not web_dir.is_dir():
        return
    per_bucket: dict[str, int] = {}
    for cell in surface.cells:
        per_bucket[cell.bucket] = per_bucket.get(cell.bucket, 0) + 1
    chosen: list[str] = []
    total = 0
    for bucket in sorted(per_bucket, reverse=True):  # newest first
        if chosen and total + per_bucket[bucket] > max_cells:
            break
        chosen.append(bucket)
        total += per_bucket[bucket]
    keep = set(chosen)
    buckets = sorted(keep)
    records = [c.as_record() for c in surface.cells if c.bucket in keep]
    payload = {
        "interval": surface.interval,
        "attribution": attribution,
        "buckets": buckets,
        "cells": records,
    }
    (web_dir / "sample-surface.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _write_web_health(
    web_dir: Path,
    raw: list[Observation],
    interval_s: float,
    *,
    coverage: dict[str, object] | None = None,
    store_dir: str | Path | None = None,
) -> None:
    """Bake the node-health summary so the static dashboard shows coverage with no live API.

    A coverage-equity block (calibrated-vs-raw per cell) rides along when provided, so the static
    site carries the same calibration-coverage read as the live ``/api/health.json``. An
    integrity block (chain head from ``digests.jsonl``, read cheaply — see ``qc.health_report``)
    rides along too when ``store_dir`` is given."""
    if not web_dir.is_dir():
        return
    report = qc.health_report(
        raw, expected_interval_s=interval_s, coverage=coverage, store_dir=store_dir
    )
    (web_dir / "sample-health.json").write_text(json.dumps(report, indent=2), encoding="utf-8")


def _write_web_alerts(web_dir: Path, surface: aggregate.Surface, config: NetworkConfig) -> None:
    """Bake the neighborhood-alerts feed (JSON + Atom) so the static site can show and syndicate it.

    Deployment-neutral relative links and data-derived timestamps keep the committed artifact
    deterministic — re-running the pipeline on the same store reproduces it byte for byte."""
    if not web_dir.is_dir():
        return
    feed = alerts.build_feed(
        surface, network=config.name, base_url="", thresholds=config.alert_thresholds or None
    )
    (web_dir / "alerts.json").write_text(json.dumps(feed.to_json(), indent=2), encoding="utf-8")
    (web_dir / "alerts.xml").write_text(feed.to_atom(), encoding="utf-8")


def _write_web_cooling_centers(web_dir: Path, source: Path) -> None:
    """Bake the validated cooling-center overlay next to the dashboard, if a dataset is present."""
    if not web_dir.is_dir() or not source.is_file():
        return
    dataset = cooling_centers.load(source)  # validate before publishing
    (web_dir / "cooling-centers.geojson").write_text(
        json.dumps(dataset.to_geojson(), indent=2), encoding="utf-8"
    )


_FetchOk = tuple[
    list[Observation], dict[str, Any], str, str, str
]  # observations, network, attribution, source label, license


def _merge_network_doc(config_path: Path, network: dict[str, Any]) -> dict[str, Any]:
    """For ``--accumulate``: union today's fetched nodes into the previously written network doc
    so a node that drops out of one day's discovery (EXP-01: "nodes that come and go") keeps its
    entry — and so its history in the store stays resolvable by ``aggregate`` — while a node seen
    again today gets its label/location refreshed. Every other top-level field (name, grid
    resolution, languages, reference monitors, calibration windows) comes from today's fetch."""
    if not config_path.is_file():
        return network
    try:
        previous = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return network  # a corrupt prior file shouldn't block today's fetch
    prior_nodes = {n["node_id"]: n for n in previous.get("nodes", []) if "node_id" in n}
    for node in network.get("nodes", []):
        prior_nodes[node["node_id"]] = node  # today's data wins for nodes seen again
    merged = dict(network)
    merged["nodes"] = list(prior_nodes.values())
    return merged


def _fetch_openaq(args: argparse.Namespace) -> _FetchOk | int:
    import os

    from .sources import openaq
    from .sources._http import SourceError

    api_key = args.api_key or os.environ.get("OPENAQ_API_KEY", "")
    if not api_key:
        _err(
            "swelter: --source openaq needs an API key (--api-key or OPENAQ_API_KEY); "
            "get a free one at https://explore.openaq.org/register"
        )
        return 1
    _err(
        f"swelter: fetching real physical sensors across California from OpenAQ "
        f"(up to {args.max_locations} sites, block-by-block)…"
    )
    try:
        observations, nodes = openaq.fetch(
            api_key, max_locations=args.max_locations, throttle_s=args.throttle
        )
    except (SourceError, OSError, ValueError) as exc:
        _err(f"swelter: fetch failed ({exc}); check your network/API key")
        return 1
    if not observations:
        _err("swelter: no readings returned from OpenAQ")
        return 1
    network = openaq.network_doc("California", nodes)
    return observations, network, openaq.ATTRIBUTION, "OpenAQ", openaq.LICENSE


def _fetch_sensor_community(args: argparse.Namespace) -> _FetchOk | int:
    from .sources import sensor_community
    from .sources._http import SourceError

    area = sensor_community.Area(args.area_name, args.lat, args.lon, args.radius)
    _err(
        f"swelter: fetching real community low-cost sensors near {area.name} "
        f"(r={area.radius_km:g} km) from Sensor.Community…"
    )
    try:
        observations, nodes = sensor_community.fetch(area)
    except (SourceError, OSError, ValueError) as exc:
        _err(f"swelter: fetch failed ({exc}); check your network connection")
        return 1
    if not observations:
        _err("swelter: no readings (Sensor.Community is sparse outside Europe — try a EU area)")
        return 1
    network = sensor_community.network_doc(area.name, nodes)
    return (
        observations,
        network,
        sensor_community.ATTRIBUTION,
        "Sensor.Community",
        sensor_community.LICENSE,
    )


def _fetch_openmeteo(args: argparse.Namespace) -> _FetchOk | int:
    from .sources import openmeteo
    from .sources._http import SourceError

    places = openmeteo.CALIFORNIA
    _err(
        f"swelter: fetching real readings for {len(places)} California cities "
        "from Open-Meteo (Copernicus CAMS air quality + weather)…"
    )
    try:
        observations = openmeteo.fetch(
            places, past_days=args.past_days, forecast_days=args.forecast_days
        )
    except (SourceError, OSError, ValueError) as exc:
        _err(f"swelter: fetch failed ({exc}); check your network connection")
        return 1
    if not observations:
        _err("swelter: no readings returned")
        return 1
    network = openmeteo.network_doc(places)
    return (
        observations,
        network,
        openmeteo.ATTRIBUTION,
        "Copernicus CAMS via Open-Meteo",
        openmeteo.LICENSE,
    )


def cmd_fetch(args: argparse.Namespace) -> int:
    """Fetch REAL readings from a live open-data source, build the surface and dashboard sample,
    and optionally serve. ``--source openmeteo`` is Copernicus CAMS model data for California cities
    (keyless, but coarse — not block-level); ``--source openaq`` is dense real physical sensors
    across California (block-by-block, needs an API key); ``--source sensor-community`` is real
    community low-cost sensors (dense in Europe). The two sensor sources are uncalibrated, so their
    readings are shown raw/provisional — swelter's thesis made real. By default the store is wiped
    first, so each fetch is a fresh snapshot; ``--accumulate`` keeps the existing store between
    runs instead (see ADR 0013), so readings pile up run over run and the time slider ends up
    with real longitudinal history rather than one fetch's worth."""
    if args.source == "openaq":
        result = _fetch_openaq(args)
    elif args.source == "sensor-community":
        result = _fetch_sensor_community(args)
    else:
        result = _fetch_openmeteo(args)
    if isinstance(result, int):
        return result
    observations, network, attribution, source_label, license = result

    observations = qc.apply(observations)
    config_path = Path(args.config)
    if args.accumulate:
        network = _merge_network_doc(config_path, network)
    config_path.write_text(yaml.safe_dump(network, sort_keys=False), encoding="utf-8")
    config = _load_config(args.config)  # parse it back so we fail loudly if the write was bad

    paths = store_paths(args.store)
    if not args.accumulate:
        paths["db"].unlink(missing_ok=True)  # a fresh snapshot each fetch; re-running is idempotent
    with SqliteStore(paths["db"]) as store:
        # write() is INSERT OR IGNORE on (node_id, timestamp, parameter, calibration), so
        # re-fetching overlapping history under --accumulate is idempotent, not duplicated.
        written = store.write(observations)
        surface = aggregate.aggregate(store.all(), config)
        paths["aggregate"].write_text(
            json.dumps(surface.snapshot_geojson(), indent=2), encoding="utf-8"
        )
        _write_web_sample(Path(args.web), surface, attribution=attribution)
        _coverage = qc.coverage_equity(store.all(), aggregate.node_cell_map(config))
        _write_web_health(
            Path(args.web),
            store.read(calibration=RAW),
            args.interval,
            coverage=_coverage,
            store_dir=args.store,
        )
        _write_web_alerts(Path(args.web), surface, config)
        _write_web_cooling_centers(Path(args.web), Path(args.cooling_centers))
        all_obs = list(store.all())
        mode = "accumulated" if args.accumulate else "stored"
        _err(
            f"swelter: {mode} {written.written} new of {len(all_obs)} total real observations "
            f"from {len(config.nodes)} locations (source: {source_label})"
        )
        _err(
            export.summarize(all_obs, gaps=qc.detect_gaps(all_obs, args.interval), license=license)
        )

    if args.serve:
        store = open_store(args.store)
        base = f"http://{args.host}:{args.port}"
        ctx = ServerContext(
            store=store,
            config=config,
            web_dir=Path(args.web),
            base_url=base,
            cooling_centers_path=_cooling_path(args.cooling_centers),
            store_dir=paths["dir"],
        )
        _err(f"swelter: serving REAL data ({source_label}) at {base}  (Ctrl-C to stop)")
        try:
            serve(ctx, host=args.host, port=args.port)
        finally:
            store.close()
    return 0


def cmd_rebuild(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    paths = store_paths(args.store)
    with open_store(args.store) as store:
        dropped = store.drop_calibrated()
        raw = store.read(calibration=RAW)
        if paths["registry"].is_file():
            registry = calibrate.CorrectionRegistry.from_yaml(paths["registry"])
            calibrated = [o for o in calibrate.apply(raw, registry) if o.calibration != RAW]
            store.write(calibrated)
            _err(f"swelter: dropped {dropped} derived rows, rebuilt {len(calibrated)} from raw")
        else:
            _err(f"swelter: dropped {dropped} derived rows; no registry to reapply")
        surface = aggregate.aggregate(store.all(), config)
    paths["aggregate"].write_text(
        json.dumps(surface.snapshot_geojson(), indent=2), encoding="utf-8"
    )
    _err(f"swelter: rebuilt surface ({len(surface.cells)} cell-hours)")
    return 0


def cmd_verify_archive(args: argparse.Namespace) -> int:
    """Recompute every stored row's content hash and (optionally) publish the chained daily digest.

    Exit nonzero the moment a single row's stored hash disagrees with what its own fields hash
    to — that is the tamper signal. ``--write`` only (re)publishes ``digests.jsonl`` when
    verification passed; a known-corrupted archive never gets a fresh, misleadingly clean head
    written over it.
    """
    with open_store(args.store) as store:
        mismatches = integrity.verify_rows(store)
        digests = integrity.daily_digests(store)
    ok = not mismatches
    rows_checked = sum(d.row_count for d in digests)
    head = digests[-1].chain if digests else ""

    written_path: Path | None = None
    if args.write:
        if ok:
            written_path = integrity.write_digests(args.store, digests)
        else:
            _err("swelter: not writing digests.jsonl — verification failed")

    if args.json:
        payload = {
            "ok": ok,
            "rows_checked": rows_checked,
            "days": len(digests),
            "head": head,
            "mismatches": [
                {
                    "node_id": m.node_id,
                    "timestamp": m.timestamp,
                    "parameter": m.parameter,
                    "calibration": m.calibration,
                    "expected": m.expected,
                    "actual": m.actual,
                }
                for m in mismatches
            ],
            "digests_path": str(written_path) if written_path else None,
        }
        print(json.dumps(payload, indent=2))
        return 0 if ok else 1

    if ok:
        _err(
            f"swelter: verify-archive OK — {rows_checked} row(s) match their stored hash "
            f"across {len(digests)} day(s)"
        )
        _err(f"  head chain  {head or '(empty store)'}")
        if written_path is not None:
            _err(f"  wrote {written_path}")
    else:
        _err(
            f"swelter: verify-archive FAILED — {len(mismatches)} of {rows_checked} row(s) do not "
            "match their stored hash"
        )
        for m in mismatches[:20]:
            _err(
                f"  MISMATCH  {m.node_id}/{m.parameter}@{m.timestamp} ({m.calibration})  "
                f"expected={m.expected[:12]}…  actual={m.actual[:12]}…"
            )
        if len(mismatches) > 20:
            _err(f"  … and {len(mismatches) - 20} more")
    return 0 if ok else 1


def cmd_snapshot(args: argparse.Namespace) -> int:
    """Freeze a citable, versioned data release: raw observations + corrections + surface, a
    MANIFEST.json with per-file SHA-256, and a dataset CITATION.cff/CITATION.txt pair. Local
    artifacts only — no external DOI service; pass --doi once a collective has minted one."""
    manifest = snapshot.build_snapshot(
        Path(args.store), Path(args.out), args.version, args.doi or None
    )
    citation_text = (Path(args.out) / snapshot.CITATION_TXT_FILENAME).read_text(encoding="utf-8")
    _err(
        f"swelter: snapshot {manifest.release_version} → {args.out} "
        f"({manifest.record_count} raw observations, {len(manifest.files)} file(s))"
    )
    for note in manifest.notes:
        _err(f"  ⚠ {note}")
    print(citation_text.strip())
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    """Scaffold a starter network.yaml so a community can stand up its own instance fast."""
    path = Path(args.config)
    if path.exists() and not args.force:
        _err(f"swelter: {path} already exists; pass --force to overwrite")
        return 1
    # JSON-quote the name so any character (colons, quotes) stays valid YAML.
    content = STARTER_NETWORK.replace("__NAME__", json.dumps(args.name))
    path.write_text(content, encoding="utf-8")
    config = load_config(str(path))  # parse it back so we fail loudly if the scaffold is malformed
    _err(f"swelter: wrote starter network → {path} ({len(config.nodes)} nodes)")
    _err("next: edit it (see docs/ADD-YOUR-NEIGHBORHOOD.md), then try the bundled demo:")
    _err("      swelter demo --serve")
    _err(f"      …or run the pipeline against your own config with --config {path}")
    return 0


def cmd_doctor(args: argparse.Namespace) -> int:
    """Validate a network.yaml loudly: report every mistake in one pass, exit nonzero on errors.

    Unlike the other subcommands (which load a config and keep going so a typo does not take down
    a running network), `doctor` is the strict gate — the thing to run before committing a
    `network.yaml` change, and the thing CI can run on a PR. It reuses the same checks
    (`config_concerns`, `label_concerns`) the other subcommands print warnings from on load.
    """
    path = Path(args.config)
    if not path.is_file():
        _err(f"swelter: config {path} not found")
        return 1
    config, doc = load_config_doc(str(path))
    errors, warnings = config_concerns(config, doc)
    warnings = [*warnings, *label_concerns(config)]
    if not errors and not warnings:
        _err(f"swelter: {path} — clean ({len(config.nodes)} nodes, no concerns)")
        return 0
    _print_concerns(errors, warnings)
    _err(
        f"swelter: {path} — {len(errors)} error(s), {len(warnings)} warning(s)"
        + (" — fix the errors above before deploying" if errors else "")
    )
    return 1 if errors else 0


def cmd_version(_: argparse.Namespace) -> int:
    print(f"swelter {__version__}")
    return 0


def cmd_crosswalk(args: argparse.Namespace) -> int:
    """Print the outbound parameter crosswalk (swelter -> OpenAQ / Sensor.Community). Read-only,
    no network — a static in-memory table (see :mod:`swelter.crosswalk`)."""
    rows = crosswalk.crosswalk_table()
    if args.format == "json":
        print(json.dumps(rows, indent=2))
        return 0
    fields = list(rows[0].keys()) if rows else []
    writer = csv.DictWriter(sys.stdout, fieldnames=fields)
    writer.writeheader()
    writer.writerows(rows)
    return 0


# -- parser ------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="swelter",
        description="Community heat and air-quality sensing network with open, calibrated data.",
    )
    parser.add_argument("--version", action="version", version=f"swelter {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    def add_store(p: argparse.ArgumentParser) -> None:
        p.add_argument("--store", default=DEFAULT_STORE, help="store directory")

    def add_config(p: argparse.ArgumentParser) -> None:
        p.add_argument("--config", default=DEFAULT_CONFIG, help="network.yaml path")

    def add_interval(p: argparse.ArgumentParser) -> None:
        p.add_argument(
            "--interval", type=float, default=DEFAULT_INTERVAL_S, help="sampling interval, seconds"
        )

    def add_cooling(p: argparse.ArgumentParser) -> None:
        p.add_argument(
            "--cooling-centers",
            default=DEFAULT_COOLING,
            help="curated cooling-center GeoJSON for the map overlay (optional)",
        )

    p_init = sub.add_parser("init", help="scaffold a starter network.yaml for a new community")
    p_init.add_argument(
        "--config", default=DEFAULT_CONFIG, help="path to write (default network.yaml)"
    )
    p_init.add_argument(
        "--name", default="My Neighborhood heat & air network", help="the network's name"
    )
    p_init.add_argument("--force", action="store_true", help="overwrite if the file already exists")
    p_init.set_defaults(func=cmd_init)

    p_ingest = sub.add_parser("ingest", help="ingest a JSONL file of node payloads")
    p_ingest.add_argument("input", help="JSONL file of node payloads")
    add_store(p_ingest)
    p_ingest.set_defaults(func=cmd_ingest)

    p_qc = sub.add_parser("qc", help="report node health, completeness, and coverage equity")
    p_qc.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    add_store(p_qc)
    add_config(p_qc)
    add_interval(p_qc)
    p_qc.set_defaults(func=cmd_qc)

    p_cal = sub.add_parser("calibrate", help="fit corrections from co-location data and apply them")
    p_cal.add_argument("--colocation", default=f"{DEFAULT_DATA}/colocation.jsonl")
    p_cal.add_argument(
        "--fit-only", action="store_true", help="fit and write registry, do not apply"
    )
    add_store(p_cal)
    add_config(p_cal)
    p_cal.set_defaults(func=cmd_calibrate)

    p_agg = sub.add_parser("aggregate", help="build the gridded heat/AQI surface")
    p_agg.add_argument("--out", default="", help="GeoJSON output path")
    add_store(p_agg)
    add_config(p_agg)
    p_agg.set_defaults(func=cmd_aggregate)

    p_cards = sub.add_parser(
        "cards",
        help="emit print-CSS bilingual neighborhood cards (door flyers / fridge cards) per cell",
    )
    p_cards.add_argument(
        "--area", default="", help="limit to one published cell (area_id, as in alerts ?area=)"
    )
    p_cards.add_argument("--lang", choices=("en", "es"), default="en", help="card language")
    p_cards.add_argument(
        "--large-type", action="store_true", help="larger base font size for low-vision printing"
    )
    p_cards.add_argument("--out", default="", help="HTML output path (default: stdout)")
    p_cards.add_argument(
        "--feed-url",
        default="",
        help="base alerts-feed URL to encode as each card's QR (?area=<cell> is added per cell)",
    )
    add_store(p_cards)
    add_config(p_cards)
    add_cooling(p_cards)
    p_cards.set_defaults(func=cmd_cards)

    p_alerts = sub.add_parser(
        "alerts", help="build the neighborhood heat/AQI alerts feed (JSON + Atom)"
    )
    p_alerts.add_argument("--format", choices=("json", "atom", "none"), default="json")
    p_alerts.add_argument(
        "--web", default="", help="also bake alerts.json + alerts.xml into this web dir"
    )
    p_alerts.add_argument(
        "--base-url", default="http://localhost:8000", help="base URL for feed self/links"
    )
    add_store(p_alerts)
    add_config(p_alerts)
    p_alerts.set_defaults(func=cmd_alerts)

    p_exp = sub.add_parser("export", help="export observations as CSV or JSON to stdout")
    p_exp.add_argument("--format", choices=("csv", "json"), default="csv")
    p_exp.add_argument("--since", default=None)
    p_exp.add_argument("--until", default=None)
    p_exp.add_argument("--node", default=None)
    p_exp.add_argument("--parameter", default=None)
    p_exp.add_argument("--bbox", default=None, help="named area (reserved; see docs/api.md)")
    p_exp.add_argument(
        "--license",
        default=export.DEFAULT_LICENSE,
        help="license of the exported data (default: CC0-1.0, the store's native default; "
        "pass the source's real terms — e.g. 'ODC-DbCL-1.0' — for a fetched third-party store)",
    )
    p_exp.add_argument(
        "--attribution", default=None, help="attribution text to carry alongside --license"
    )
    add_store(p_exp)
    add_interval(p_exp)
    p_exp.set_defaults(func=cmd_export)

    p_serve = sub.add_parser("serve", help="serve the dashboard, API, and exports (read-only)")
    p_serve.add_argument("--host", default="127.0.0.1")
    p_serve.add_argument("--port", type=int, default=8000)
    p_serve.add_argument("--web", default=DEFAULT_WEB)
    add_store(p_serve)
    add_config(p_serve)
    add_cooling(p_serve)
    p_serve.set_defaults(func=cmd_serve)

    p_iserve = sub.add_parser(
        "ingest-serve",
        help="run the authenticated node write path (write-only listener, per-node HMAC)",
    )
    p_iserve.add_argument("--host", default="127.0.0.1")
    p_iserve.add_argument("--port", type=int, default=8100)
    p_iserve.add_argument(
        "--keys", default=DEFAULT_KEYS, help="operator-local node-keys file (swelter node-key)"
    )
    p_iserve.add_argument(
        "--skew",
        type=float,
        default=ingest_server.DEFAULT_SKEW_S,
        help="replay window: max seconds between a request's signed timestamp and server time",
    )
    add_store(p_iserve)
    p_iserve.set_defaults(func=cmd_ingest_serve)

    p_key = sub.add_parser(
        "node-key", help="issue or rotate a node's ingest HMAC key (operator-local keys file)"
    )
    p_key.add_argument("node_id", help="the host-assigned node id the key authenticates")
    p_key.add_argument(
        "--keys", default=DEFAULT_KEYS, help="operator-local node-keys file to create/update"
    )
    p_key.set_defaults(func=cmd_node_key)

    p_preview = sub.add_parser(
        "node-preview", help="show a host the exact coordinate the map/API publishes for a node"
    )
    p_preview.add_argument(
        "node_id", nargs="?", default=None, help="show one node (default: every placed node)"
    )
    add_config(p_preview)
    p_preview.set_defaults(func=cmd_node_preview)

    p_demo = sub.add_parser("demo", help="replay recorded data through the whole pipeline")
    p_demo.add_argument("--data", default=DEFAULT_DATA)
    p_demo.add_argument("--store", default=f"{DEFAULT_STORE}/demo")
    p_demo.add_argument("--serve", action="store_true", help="serve the dashboard after replaying")
    p_demo.add_argument("--host", default="127.0.0.1")
    p_demo.add_argument("--port", type=int, default=8000)
    p_demo.add_argument("--web", default=DEFAULT_WEB)
    add_config(p_demo)
    add_interval(p_demo)
    add_cooling(p_demo)
    p_demo.set_defaults(func=cmd_demo)

    p_fetch = sub.add_parser(
        "fetch",
        help="fetch REAL readings from a live open-data source and build the dashboard",
    )
    p_fetch.add_argument(
        "--source",
        choices=("openmeteo", "openaq", "sensor-community"),
        default="openmeteo",
        help="openmeteo: Copernicus CAMS model data, California (keyless, coarse); "
        "openaq: dense real sensors, California, block-by-block (needs API key); "
        "sensor-community: real community low-cost sensors (dense in Europe)",
    )
    p_fetch.add_argument("--store", default=f"{DEFAULT_STORE}/real")
    p_fetch.add_argument("--config", default="network.real.yaml", help="where to write the network")
    p_fetch.add_argument("--web", default=DEFAULT_WEB)
    p_fetch.add_argument(
        "--accumulate",
        action="store_true",
        help="keep the existing store between runs instead of wiping it first, so history "
        "builds up across repeated fetches (e.g. daily CI) instead of one snapshot per run",
    )
    p_fetch.add_argument(
        "--past-days", type=int, default=2, help="openmeteo: history window (days)"
    )
    p_fetch.add_argument("--forecast-days", type=int, default=1)
    # openaq (real California sensors — block-by-block):
    p_fetch.add_argument("--api-key", default="", help="openaq: API key (or set OPENAQ_API_KEY)")
    p_fetch.add_argument("--max-locations", type=int, default=200, help="openaq: site cap")
    p_fetch.add_argument(
        "--throttle", type=float, default=1.1, help="openaq: seconds between calls"
    )
    # sensor-community area (defaults to Stuttgart, where coverage is dense):
    p_fetch.add_argument("--area-name", default="Stuttgart", help="sensor-community: area label")
    p_fetch.add_argument("--lat", type=float, default=48.7758, help="sensor-community: centre lat")
    p_fetch.add_argument("--lon", type=float, default=9.1829, help="sensor-community: centre lon")
    p_fetch.add_argument("--radius", type=float, default=30.0, help="sensor-community: radius km")
    p_fetch.add_argument("--serve", action="store_true", help="serve the dashboard after fetching")
    p_fetch.add_argument("--host", default="127.0.0.1")
    p_fetch.add_argument("--port", type=int, default=8000)
    add_interval(p_fetch)
    add_cooling(p_fetch)
    p_fetch.set_defaults(func=cmd_fetch)

    p_rebuild = sub.add_parser("rebuild", help="rebuild calibrated + surface from immutable raw")
    add_store(p_rebuild)
    add_config(p_rebuild)
    p_rebuild.set_defaults(func=cmd_rebuild)

    p_doctor = sub.add_parser(
        "doctor", help="validate network.yaml loudly; exit nonzero on any error"
    )
    add_config(p_doctor)
    p_doctor.set_defaults(func=cmd_doctor)

    p_snap = sub.add_parser(
        "snapshot",
        help="freeze a citable, versioned data release (MANIFEST + dataset CITATION.cff/.txt)",
    )
    add_store(p_snap)
    p_snap.add_argument("--out", default="dist/snapshot", help="directory to write the release to")
    p_snap.add_argument(
        "--version", default=__version__, help="release version (defaults to the swelter version)"
    )
    p_snap.add_argument(
        "--doi",
        default="",
        help="DOI for this release, if one has been minted (e.g. via Zenodo/DataCite); "
        "omit for a clearly-labelled placeholder",
    )
    p_snap.set_defaults(func=cmd_snapshot)

    p_verify = sub.add_parser(
        "verify-archive",
        help="recompute row hashes and publish a chained daily digest (tamper-evidence)",
    )
    add_store(p_verify)
    p_verify.add_argument(
        "--write", action="store_true", help="(re)write digests.jsonl in the store folder"
    )
    p_verify.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    p_verify.set_defaults(func=cmd_verify_archive)

    p_version = sub.add_parser("version", help="print the swelter version")
    p_version.set_defaults(func=cmd_version)

    p_cross = sub.add_parser(
        "crosswalk",
        help="print the outbound parameter crosswalk (swelter -> OpenAQ / Sensor.Community)",
    )
    p_cross.add_argument("--format", choices=("csv", "json"), default="csv")
    p_cross.set_defaults(func=cmd_crosswalk)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    func = args.func
    result: int = func(args)
    return result


if __name__ == "__main__":
    raise SystemExit(main())
