"""The ``swelter`` command line: ingest, qc, calibrate, aggregate, export, serve, demo, rebuild —
plus the operator-side write path (ingest-serve, node-key).

This is the one-command surface a neighbourhood collective actually touches. Every subcommand
is a thin wrapper over the library functions, so anything the CLI does is equally scriptable
and testable. ``swelter demo`` is the keystone: it replays the recorded week in ``data/demo``
through the whole pipeline — ingest → calibrate → aggregate → export — and optionally serves
the dashboard, with no hardware in the loop.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any, cast

import yaml

from . import (
    __version__,
    aggregate,
    alerts,
    calibrate,
    cooling_centers,
    crosswalk,
    export,
    ingest,
    ingest_server,
    plan,
    qc,
)
from .config import NetworkConfig, consent_concerns, label_concerns, load_config
from .models import RAW, Observation
from .server import ServerContext, serve
from .store import SqliteStore, open_store, store_paths

DEFAULT_STORE = "store"
DEFAULT_CONFIG = "network.yaml"
DEFAULT_WEB = "web"
DEFAULT_DATA = "data/demo"
DEFAULT_COOLING = "data/cooling_centers.geojson"
DEFAULT_INTERVAL_S = 3600.0
DEFAULT_KEYS = "node-keys.yaml"  # operator-local; outside network.yaml and the copyable store

#: A minimal, commented starter network written by `swelter init`. __NAME__ is replaced with a
#: YAML-safe quoted name. Two nodes, one reference monitor, one co-location window — the smallest
#: thing that runs end to end, ready to edit. The full guide is docs/ADD-YOUR-NEIGHBORHOOD.md.
STARTER_NETWORK = """\
# swelter network — generated by `swelter init`. Edit it to describe your own network.
# Guide: docs/ADD-YOUR-NEIGHBORHOOD.md. Privacy: every coordinate snaps to a grid_resolution_m cell
# unless a host opts a node into `location: precise` — a collective decision (docs/governance.md).

name: __NAME__
grid_resolution_m: 150          # published cell size in metres (~a block); a collective decision
languages:
- en
- es

reference_monitors:             # the trusted station(s) you co-locate against to earn calibration
- monitor_id: ref-aqs-0001
  label: Regulatory AQS station (your city)
  source: US EPA AQS site XX-XXX-XXXX

nodes:                          # one entry per sensor location; node_id is the ONLY identifier
- node_id: node-01
  label: Cedar & 4th            # a place-name residents say out loud
  lat: 38.575057                # any coordinate inside the cell; published coarse unless `precise`
  lon: -121.509361
  location: coarse
- node_id: node-02
  label: Oak & 4th
  lat: 38.575120
  lon: -121.506400
  location: coarse

calibration_windows:            # one per (node, parameter); a node with none stays raw/provisional
- node_id: node-01
  reference: ref-aqs-0001
  parameter: pm25_ugm3
  start: '2026-06-01T00:00:00Z'
  end: '2026-06-03T23:00:00Z'
"""


def _err(message: str) -> None:
    print(message, file=sys.stderr)


def _load_config(path: str) -> NetworkConfig:
    if Path(path).is_file():
        config = load_config(path)
        for concern in label_concerns(config):
            _err(f"swelter: ⚠ {concern}")
        for concern in consent_concerns(config):
            _err(f"swelter: ⚠ {concern}")
        return config
    _err(f"swelter: config {path} not found; using an empty network")
    return NetworkConfig()


# -- subcommands -------------------------------------------------------------


def cmd_ingest(args: argparse.Namespace) -> int:
    if not Path(args.input).is_file():
        _err(f"swelter: input {args.input} not found")
        return 1
    paths = store_paths(args.store)
    with open_store(args.store) as store:
        result = ingest.ingest_file(args.input, store, quarantine_path=paths["quarantine"])
    _err(
        f"swelter: ingested {result.accepted_payloads} payloads → "
        f"{result.observations_written} new observations "
        f"({result.duplicates} duplicates, {result.quarantined} quarantined)"
    )
    return 0


def cmd_qc(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    with open_store(args.store) as store:
        raw = store.read(calibration=RAW)
        all_obs = list(store.all())
    if not raw:
        _err("swelter: store is empty")
        return 0
    latest = max(o.timestamp for o in raw)
    gaps = qc.detect_gaps(raw, args.interval)
    health = qc.node_health(
        raw, latest, offline_after_s=args.interval * 3, expected_interval_s=args.interval
    )
    # Coverage-equity: calibrated-vs-raw node counts per published cell, so an under-calibrated
    # block is visible rather than hidden behind the network average (audit B3). Descriptive
    # coverage, not a ranking of neighborhoods (see qc.coverage_equity / docs/RESEARCH-ROADMAP).
    coverage = qc.coverage_equity(all_obs, aggregate.node_cell_map(config))
    cov = cast(dict[str, Any], coverage["summary"])
    if args.json:
        payload = {
            "nodes": [
                {
                    "node_id": n.node_id,
                    "status": n.status,
                    "observations": n.observations,
                    "completeness": n.completeness,
                    "flagged_fraction": round(n.flagged_fraction, 3),
                    "online": n.online,
                    "last_seen": n.last_seen,
                }
                for n in health
            ],
            "gaps": [
                {
                    "node_id": g.node_id,
                    "parameter": g.parameter,
                    "start": g.start,
                    "end": g.end,
                    "minutes": round(g.seconds / 60),
                }
                for g in gaps
            ],
            "coverage_equity": coverage,
        }
        print(json.dumps(payload, indent=2))
        return 0
    not_ok = sum(1 for n in health if n.status != "ok")
    _err(
        f"swelter: {len(health)} nodes ({not_ok} degraded/offline), {len(gaps)} gaps "
        f"over interval {int(args.interval)}s"
    )
    for gap in gaps[:10]:
        _err(
            f"  gap  {gap.node_id}/{gap.parameter}  {gap.start} → {gap.end}  "
            f"({round(gap.seconds / 60)} min)"
        )
    for node in health:
        _err(
            f"  {node.node_id:>10}  {node.status.upper():<8}  {node.observations:>6} obs  "
            f"{node.completeness * 100:5.1f}% complete  {node.flagged_fraction * 100:5.1f}% flagged"
        )
    _err(
        f"swelter: coverage — {cov['calibrated_nodes']}/{cov['nodes']} nodes calibrated, "
        f"{cov['confirmed_cells']}/{cov['cells']} cells confirmed, "
        f"{cov['provisional_cells']} provisional cell(s)"
    )
    for cell in cast(list[dict[str, Any]], coverage["cells"]):
        if not cell["confirmed"]:
            name = cell["label"] or cell["cell_id"]
            _err(
                f"  provisional cell  {name}  "
                f"({cell['calibrated_nodes']}/{cell['nodes']} calibrated)"
            )
    return 0


def cmd_calibrate(args: argparse.Namespace) -> int:
    if not Path(args.colocation).is_file():
        _err(f"swelter: colocation {args.colocation} not found")
        return 1
    pairs = calibrate.read_colocation(args.colocation)
    registry = calibrate.fit(pairs)
    paths = store_paths(args.store)
    registry.to_yaml(paths["registry"])
    _err(f"swelter: fit {len(registry)} corrections → {paths['registry']}")
    for c in registry.all():
        _err(f"  {c.version:<28} n={c.n:<4} R²={c.r2:.3f}  ±{c.residual_std} {c.parameter}")
    if not args.fit_only:
        with open_store(args.store) as store:
            raw = store.read(calibration=RAW)
            store.drop_calibrated()
            calibrated = [o for o in calibrate.apply(raw, registry) if o.calibration != RAW]
            written = store.write(calibrated)
        _err(f"swelter: applied corrections → {written.written} calibrated observations")
    return 0


def cmd_aggregate(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    with open_store(args.store) as store:
        surface = aggregate.aggregate(store.all(), config)
    out = Path(args.out or store_paths(args.store)["aggregate"])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(surface.snapshot_geojson(), indent=2), encoding="utf-8")
    _err(f"swelter: {len(surface.cells)} cell-hours → {out}")
    return 0


def cmd_alerts(args: argparse.Namespace) -> int:
    """Build the neighborhood heat/AQI alerts feed (JSON + Atom) from the current surface."""
    config = _load_config(args.config)
    with open_store(args.store) as store:
        surface = aggregate.aggregate(store.all(), config)
    feed = alerts.build_feed(
        surface,
        network=config.name,
        base_url=args.base_url,
        thresholds=config.alert_thresholds or None,
    )
    if args.format == "atom":
        sys.stdout.write(feed.to_atom())
    elif args.format == "json":
        sys.stdout.write(json.dumps(feed.to_json(), indent=2) + "\n")
    if args.web:
        _write_web_alerts(Path(args.web), surface, config)
        _err(f"swelter: wrote alerts.json + alerts.xml → {args.web}/")
    _err(f"swelter: {len(feed.alerts)} active alert(s) at {feed.bucket or 'no data'}")
    return 0


def cmd_export(args: argparse.Namespace) -> int:
    with open_store(args.store) as store:
        observations = store.read(
            parameter=args.parameter, node_id=args.node, since=args.since, until=args.until
        )
        raw = store.read(calibration=RAW)
    gaps = qc.detect_gaps(raw, args.interval)
    if args.format == "json":
        sys.stdout.write(export.to_json(observations, indent=2))
    else:
        sys.stdout.write(export.to_csv(observations))
    _err(export.summarize(observations, gaps=gaps))
    return 0


def _cooling_path(path: str) -> Path | None:
    """The cooling-center dataset path if it exists, else ``None`` (overlay simply stays empty)."""
    p = Path(path)
    return p if p.is_file() else None


def cmd_serve(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    store = open_store(args.store)
    base = f"http://{args.host}:{args.port}"
    ctx = ServerContext(
        store=store,
        config=config,
        web_dir=Path(args.web),
        base_url=base,
        cooling_centers_path=_cooling_path(args.cooling_centers),
    )
    _err(f"swelter: serving dashboard + API at {base}  (Ctrl-C to stop)")
    _err(f"  dashboard {base}/   ·   SensorThings {base}/v1.1   ·   export {base}/export.csv")
    try:
        serve(ctx, host=args.host, port=args.port)
    finally:
        store.close()
    return 0


def cmd_ingest_serve(args: argparse.Namespace) -> int:
    """Run the authenticated node write path: a write-only listener, per-node HMAC keys.

    Kept out of ``swelter serve`` on purpose — the public read surface and the node write
    surface are different trust boundaries and stay in different processes.
    """
    keys_path = Path(args.keys)
    if not keys_path.is_file():
        _err(f"swelter: keys file {args.keys} not found")
        _err(f"  issue one key per node first:  swelter node-key <node_id> --keys {args.keys}")
        return 1
    try:
        keys = ingest_server.load_keys(keys_path)
    except ingest_server.KeyfileError as exc:
        _err(f"swelter: {exc}")
        return 1
    if not keys:
        _err(f"swelter: keys file {args.keys} holds no node keys; issue them with swelter node-key")
        return 1
    paths = store_paths(args.store)
    store = open_store(args.store)
    ctx = ingest_server.IngestServerContext(
        store=store,
        keys=keys,
        quarantine_path=paths["quarantine"],
        skew_s=args.skew,
    )
    base = f"http://{args.host}:{args.port}"
    route = ingest_server.INGEST_ROUTE
    _err(f"swelter: ingest listener (write-only, per-node HMAC) at {base}{route}")
    _err(
        f"  {len(keys)} node key(s) from {args.keys} · replay window ±{int(args.skew)}s · "
        f"auth failures → {paths['quarantine']}  (Ctrl-C to stop)"
    )
    try:
        ingest_server.serve(ctx, host=args.host, port=args.port)
    finally:
        store.close()
    return 0


def cmd_node_key(args: argparse.Namespace) -> int:
    """Issue (or rotate) a node's ingest key into the operator-local keys file.

    Prints the key to stdout — the one moment it is visible — for the operator to copy into the
    node's uncommitted ``config.py``. Who gets a key, and when one is rotated or revoked, is a
    collective decision (docs/governance.md); this command is just the mechanism.
    """
    try:
        key = ingest_server.issue_key(Path(args.keys), args.node_id)
    except ingest_server.KeyfileError as exc:
        _err(f"swelter: {exc}")
        return 1
    _err(f"swelter: issued ingest key for {args.node_id} → {args.keys} (owner-only, mode 0600)")
    _err("  copy the key below into the node's uncommitted config.py as `ingest_key`.")
    _err("  never commit it, never put it in network.yaml, never publish the keys file;")
    _err("  re-running this command for the same node rotates (replaces) the key.")
    print(key)
    return 0


def cmd_demo(args: argparse.Namespace) -> int:
    data = Path(args.data)
    config = _load_config(args.config)
    paths = store_paths(args.store)
    paths["db"].unlink(missing_ok=True)  # a fresh demo store every run; replay is idempotent

    with SqliteStore(paths["db"]) as store:
        result = ingest.ingest_file(
            data / "observations.jsonl", store, quarantine_path=paths["quarantine"]
        )
        _err(f"swelter demo: replayed {result.observations_seen} observations from recorded data")

        colocation = data / "colocation.jsonl"
        if colocation.is_file():
            registry = calibrate.fit(calibrate.read_colocation(colocation))
            registry.to_yaml(paths["registry"])
            raw = store.read(calibration=RAW)
            calibrated = [o for o in calibrate.apply(raw, registry) if o.calibration != RAW]
            store.write(calibrated)
            _err(
                f"swelter demo: fit {len(registry)} corrections, wrote {len(calibrated)} calibrated"
            )

        surface = aggregate.aggregate(store.all(), config)
        paths["aggregate"].write_text(
            json.dumps(surface.snapshot_geojson(), indent=2), encoding="utf-8"
        )
        _write_web_sample(
            Path(args.web),
            surface,
            attribution="Synthetic demonstration data — no real sensors (gen_demo_data.py).",
        )
        _coverage = qc.coverage_equity(store.all(), aggregate.node_cell_map(config))
        _write_web_health(
            Path(args.web), store.read(calibration=RAW), args.interval, coverage=_coverage
        )
        _write_web_alerts(Path(args.web), surface, config)
        _write_web_cooling_centers(Path(args.web), Path(args.cooling_centers))
        all_obs = list(store.all())
        gaps = qc.detect_gaps(store.read(calibration=RAW), args.interval)
        _err(export.summarize(all_obs, gaps=gaps))

    if args.serve:
        store = open_store(args.store)
        base = f"http://{args.host}:{args.port}"
        ctx = ServerContext(
            store=store,
            config=config,
            web_dir=Path(args.web),
            base_url=base,
            cooling_centers_path=_cooling_path(args.cooling_centers),
        )
        _err(f"swelter demo: serving at {base}  (Ctrl-C to stop)")
        try:
            serve(ctx, host=args.host, port=args.port)
        finally:
            store.close()
    return 0


def _write_web_sample(
    web_dir: Path, surface: aggregate.Surface, *, attribution: str = "", max_cells: int = 4000
) -> None:
    """Refresh the dashboard's offline fallback if web/ exists, capped to keep the static payload
    light on a host like GitHub Pages — the most recent hourly buckets up to ~``max_cells`` cells,
    so a large network does not bloat the committed sample (the live API has the full history)."""
    if not web_dir.is_dir():
        return
    per_bucket: dict[str, int] = {}
    for cell in surface.cells:
        per_bucket[cell.bucket] = per_bucket.get(cell.bucket, 0) + 1
    chosen: list[str] = []
    total = 0
    for bucket in sorted(per_bucket, reverse=True):  # newest first
        if chosen and total + per_bucket[bucket] > max_cells:
            break
        chosen.append(bucket)
        total += per_bucket[bucket]
    keep = set(chosen)
    buckets = sorted(keep)
    records = [c.as_record() for c in surface.cells if c.bucket in keep]
    payload = {
        "interval": surface.interval,
        "attribution": attribution,
        "buckets": buckets,
        "cells": records,
    }
    (web_dir / "sample-surface.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _write_web_health(
    web_dir: Path,
    raw: list[Observation],
    interval_s: float,
    *,
    coverage: dict[str, object] | None = None,
) -> None:
    """Bake the node-health summary so the static dashboard shows coverage with no live API.

    A coverage-equity block (calibrated-vs-raw per cell) rides along when provided, so the static
    site carries the same calibration-coverage read as the live ``/api/health.json``."""
    if not web_dir.is_dir():
        return
    report = qc.health_report(raw, expected_interval_s=interval_s, coverage=coverage)
    (web_dir / "sample-health.json").write_text(json.dumps(report, indent=2), encoding="utf-8")


def _write_web_alerts(web_dir: Path, surface: aggregate.Surface, config: NetworkConfig) -> None:
    """Bake the neighborhood-alerts feed (JSON + Atom) so the static site can show and syndicate it.

    Deployment-neutral relative links and data-derived timestamps keep the committed artifact
    deterministic — re-running the pipeline on the same store reproduces it byte for byte."""
    if not web_dir.is_dir():
        return
    feed = alerts.build_feed(
        surface, network=config.name, base_url="", thresholds=config.alert_thresholds or None
    )
    (web_dir / "alerts.json").write_text(json.dumps(feed.to_json(), indent=2), encoding="utf-8")
    (web_dir / "alerts.xml").write_text(feed.to_atom(), encoding="utf-8")


def _write_web_cooling_centers(web_dir: Path, source: Path) -> None:
    """Bake the validated cooling-center overlay next to the dashboard, if a dataset is present."""
    if not web_dir.is_dir() or not source.is_file():
        return
    dataset = cooling_centers.load(source)  # validate before publishing
    (web_dir / "cooling-centers.geojson").write_text(
        json.dumps(dataset.to_geojson(), indent=2), encoding="utf-8"
    )


_FetchOk = tuple[
    list[Observation], dict[str, Any], str, str
]  # observations, network, attrib, label


def _merge_network_doc(config_path: Path, network: dict[str, Any]) -> dict[str, Any]:
    """For ``--accumulate``: union today's fetched nodes into the previously written network doc
    so a node that drops out of one day's discovery (EXP-01: "nodes that come and go") keeps its
    entry — and so its history in the store stays resolvable by ``aggregate`` — while a node seen
    again today gets its label/location refreshed. Every other top-level field (name, grid
    resolution, languages, reference monitors, calibration windows) comes from today's fetch."""
    if not config_path.is_file():
        return network
    try:
        previous = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return network  # a corrupt prior file shouldn't block today's fetch
    prior_nodes = {n["node_id"]: n for n in previous.get("nodes", []) if "node_id" in n}
    for node in network.get("nodes", []):
        prior_nodes[node["node_id"]] = node  # today's data wins for nodes seen again
    merged = dict(network)
    merged["nodes"] = list(prior_nodes.values())
    return merged


def _fetch_openaq(args: argparse.Namespace) -> _FetchOk | int:
    import os

    from .sources import openaq
    from .sources._http import SourceError

    api_key = args.api_key or os.environ.get("OPENAQ_API_KEY", "")
    if not api_key:
        _err(
            "swelter: --source openaq needs an API key (--api-key or OPENAQ_API_KEY); "
            "get a free one at https://explore.openaq.org/register"
        )
        return 1
    _err(
        f"swelter: fetching real physical sensors across California from OpenAQ "
        f"(up to {args.max_locations} sites, block-by-block)…"
    )
    try:
        observations, nodes = openaq.fetch(
            api_key, max_locations=args.max_locations, throttle_s=args.throttle
        )
    except (SourceError, OSError, ValueError) as exc:
        _err(f"swelter: fetch failed ({exc}); check your network/API key")
        return 1
    if not observations:
        _err("swelter: no readings returned from OpenAQ")
        return 1
    network = openaq.network_doc("California", nodes)
    return observations, network, openaq.ATTRIBUTION, "OpenAQ"


def _fetch_sensor_community(args: argparse.Namespace) -> _FetchOk | int:
    from .sources import sensor_community
    from .sources._http import SourceError

    area = sensor_community.Area(args.area_name, args.lat, args.lon, args.radius)
    _err(
        f"swelter: fetching real community low-cost sensors near {area.name} "
        f"(r={area.radius_km:g} km) from Sensor.Community…"
    )
    try:
        observations, nodes = sensor_community.fetch(area)
    except (SourceError, OSError, ValueError) as exc:
        _err(f"swelter: fetch failed ({exc}); check your network connection")
        return 1
    if not observations:
        _err("swelter: no readings (Sensor.Community is sparse outside Europe — try a EU area)")
        return 1
    network = sensor_community.network_doc(area.name, nodes)
    return observations, network, sensor_community.ATTRIBUTION, "Sensor.Community"


def _fetch_openmeteo(args: argparse.Namespace) -> _FetchOk | int:
    from .sources import openmeteo
    from .sources._http import SourceError

    places = openmeteo.CALIFORNIA
    _err(
        f"swelter: fetching real readings for {len(places)} California cities "
        "from Open-Meteo (Copernicus CAMS air quality + weather)…"
    )
    try:
        observations = openmeteo.fetch(
            places, past_days=args.past_days, forecast_days=args.forecast_days
        )
    except (SourceError, OSError, ValueError) as exc:
        _err(f"swelter: fetch failed ({exc}); check your network connection")
        return 1
    if not observations:
        _err("swelter: no readings returned")
        return 1
    network = openmeteo.network_doc(places)
    return observations, network, openmeteo.ATTRIBUTION, "Copernicus CAMS via Open-Meteo"


def cmd_fetch(args: argparse.Namespace) -> int:
    """Fetch REAL readings from a live open-data source, build the surface and dashboard sample,
    and optionally serve. ``--source openmeteo`` is Copernicus CAMS model data for California cities
    (keyless, but coarse — not block-level); ``--source openaq`` is dense real physical sensors
    across California (block-by-block, needs an API key); ``--source sensor-community`` is real
    community low-cost sensors (dense in Europe). The two sensor sources are uncalibrated, so their
    readings are shown raw/provisional — swelter's thesis made real. By default the store is wiped
    first, so each fetch is a fresh snapshot; ``--accumulate`` keeps the existing store between
    runs instead (see ADR 0013), so readings pile up run over run and the time slider ends up
    with real longitudinal history rather than one fetch's worth."""
    if args.source == "openaq":
        result = _fetch_openaq(args)
    elif args.source == "sensor-community":
        result = _fetch_sensor_community(args)
    else:
        result = _fetch_openmeteo(args)
    if isinstance(result, int):
        return result
    observations, network, attribution, source_label = result

    observations = qc.apply(observations)
    config_path = Path(args.config)
    if args.accumulate:
        network = _merge_network_doc(config_path, network)
    config_path.write_text(yaml.safe_dump(network, sort_keys=False), encoding="utf-8")
    config = load_config(args.config)

    paths = store_paths(args.store)
    if not args.accumulate:
        paths["db"].unlink(missing_ok=True)  # a fresh snapshot each fetch; re-running is idempotent
    with SqliteStore(paths["db"]) as store:
        # write() is INSERT OR IGNORE on (node_id, timestamp, parameter, calibration), so
        # re-fetching overlapping history under --accumulate is idempotent, not duplicated.
        written = store.write(observations)
        surface = aggregate.aggregate(store.all(), config)
        paths["aggregate"].write_text(
            json.dumps(surface.snapshot_geojson(), indent=2), encoding="utf-8"
        )
        _write_web_sample(Path(args.web), surface, attribution=attribution)
        _coverage = qc.coverage_equity(store.all(), aggregate.node_cell_map(config))
        _write_web_health(
            Path(args.web), store.read(calibration=RAW), args.interval, coverage=_coverage
        )
        _write_web_alerts(Path(args.web), surface, config)
        _write_web_cooling_centers(Path(args.web), Path(args.cooling_centers))
        all_obs = list(store.all())
        mode = "accumulated" if args.accumulate else "stored"
        _err(
            f"swelter: {mode} {written.written} new of {len(all_obs)} total real observations "
            f"from {len(config.nodes)} locations (source: {source_label})"
        )
        _err(export.summarize(all_obs, gaps=qc.detect_gaps(all_obs, args.interval)))

    if args.serve:
        store = open_store(args.store)
        base = f"http://{args.host}:{args.port}"
        ctx = ServerContext(
            store=store,
            config=config,
            web_dir=Path(args.web),
            base_url=base,
            cooling_centers_path=_cooling_path(args.cooling_centers),
        )
        _err(f"swelter: serving REAL data ({source_label}) at {base}  (Ctrl-C to stop)")
        try:
            serve(ctx, host=args.host, port=args.port)
        finally:
            store.close()
    return 0


def cmd_rebuild(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    paths = store_paths(args.store)
    with open_store(args.store) as store:
        dropped = store.drop_calibrated()
        raw = store.read(calibration=RAW)
        if paths["registry"].is_file():
            registry = calibrate.CorrectionRegistry.from_yaml(paths["registry"])
            calibrated = [o for o in calibrate.apply(raw, registry) if o.calibration != RAW]
            store.write(calibrated)
            _err(f"swelter: dropped {dropped} derived rows, rebuilt {len(calibrated)} from raw")
        else:
            _err(f"swelter: dropped {dropped} derived rows; no registry to reapply")
        surface = aggregate.aggregate(store.all(), config)
    paths["aggregate"].write_text(
        json.dumps(surface.snapshot_geojson(), indent=2), encoding="utf-8"
    )
    _err(f"swelter: rebuilt surface ({len(surface.cells)} cell-hours)")
    return 0


def _parse_lat_lon(raw: str) -> tuple[float, float] | None:
    """Parse a ``"lat,lon"`` string; ``None`` on anything that is not exactly two numbers."""
    parts = raw.split(",")
    if len(parts) != 2:
        return None
    try:
        return (float(parts[0].strip()), float(parts[1].strip()))
    except ValueError:
        return None


def cmd_plan(args: argparse.Namespace) -> int:
    """Siting what-if: simulate a candidate node's coverage, redundancy, and reference distance
    before any hardware moves (EXP-08). Pure function over the current config — descriptive
    numbers only, never an "optimal placement" score."""
    parsed = _parse_lat_lon(args.add_node)
    if parsed is None:
        _err(f'swelter: --add-node expects "lat,lon", got {args.add_node!r}')
        return 1
    lat, lon = parsed
    config = _load_config(args.config)
    result = plan.simulate_add_node(config, lat, lon)
    if args.json:
        print(json.dumps(result))
        return 0
    cell = cast(dict[str, float], result["candidate_cell"])
    _err(
        f"swelter: candidate cell {cell['lat']:.6f},{cell['lon']:.6f} — "
        f"{'new coverage' if result['new_cell'] else 'already covered'}"
    )
    _err(f"  redundancy: {result['redundancy']} existing node(s) already in this cell")
    nearest_node = cast("dict[str, Any] | None", result["nearest_node"])
    if nearest_node is not None:
        _err(f"  nearest node: {nearest_node['node_id']} ({nearest_node['distance_m']:.1f} m)")
    else:
        _err("  nearest node: none placed yet")
    nearest_ref = cast("dict[str, Any] | None", result["nearest_reference"])
    if nearest_ref is not None:
        _err(
            f"  nearest reference monitor: {nearest_ref['monitor_id']} "
            f"({nearest_ref['distance_m']:.1f} m)"
        )
    elif result["reference_note"]:
        _err(f"  {result['reference_note']}")
    else:
        _err("  no reference monitors configured")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    """Scaffold a starter network.yaml so a community can stand up its own instance fast."""
    path = Path(args.config)
    if path.exists() and not args.force:
        _err(f"swelter: {path} already exists; pass --force to overwrite")
        return 1
    # JSON-quote the name so any character (colons, quotes) stays valid YAML.
    content = STARTER_NETWORK.replace("__NAME__", json.dumps(args.name))
    path.write_text(content, encoding="utf-8")
    config = load_config(str(path))  # parse it back so we fail loudly if the scaffold is malformed
    _err(f"swelter: wrote starter network → {path} ({len(config.nodes)} nodes)")
    _err("next: edit it (see docs/ADD-YOUR-NEIGHBORHOOD.md), then try the bundled demo:")
    _err("      swelter demo --serve")
    _err(f"      …or run the pipeline against your own config with --config {path}")
    return 0


def cmd_version(_: argparse.Namespace) -> int:
    print(f"swelter {__version__}")
    return 0


def cmd_crosswalk(args: argparse.Namespace) -> int:
    """Print the outbound parameter crosswalk (swelter -> OpenAQ / Sensor.Community). Read-only,
    no network — a static in-memory table (see :mod:`swelter.crosswalk`)."""
    rows = crosswalk.crosswalk_table()
    if args.format == "json":
        print(json.dumps(rows, indent=2))
        return 0
    fields = list(rows[0].keys()) if rows else []
    writer = csv.DictWriter(sys.stdout, fieldnames=fields)
    writer.writeheader()
    writer.writerows(rows)
    return 0


# -- parser ------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="swelter",
        description="Community heat and air-quality sensing network with open, calibrated data.",
    )
    parser.add_argument("--version", action="version", version=f"swelter {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    def add_store(p: argparse.ArgumentParser) -> None:
        p.add_argument("--store", default=DEFAULT_STORE, help="store directory")

    def add_config(p: argparse.ArgumentParser) -> None:
        p.add_argument("--config", default=DEFAULT_CONFIG, help="network.yaml path")

    def add_interval(p: argparse.ArgumentParser) -> None:
        p.add_argument(
            "--interval", type=float, default=DEFAULT_INTERVAL_S, help="sampling interval, seconds"
        )

    def add_cooling(p: argparse.ArgumentParser) -> None:
        p.add_argument(
            "--cooling-centers",
            default=DEFAULT_COOLING,
            help="curated cooling-center GeoJSON for the map overlay (optional)",
        )

    p_init = sub.add_parser("init", help="scaffold a starter network.yaml for a new community")
    p_init.add_argument(
        "--config", default=DEFAULT_CONFIG, help="path to write (default network.yaml)"
    )
    p_init.add_argument(
        "--name", default="My Neighborhood heat & air network", help="the network's name"
    )
    p_init.add_argument("--force", action="store_true", help="overwrite if the file already exists")
    p_init.set_defaults(func=cmd_init)

    p_ingest = sub.add_parser("ingest", help="ingest a JSONL file of node payloads")
    p_ingest.add_argument("input", help="JSONL file of node payloads")
    add_store(p_ingest)
    p_ingest.set_defaults(func=cmd_ingest)

    p_qc = sub.add_parser("qc", help="report node health, completeness, and coverage equity")
    p_qc.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    add_store(p_qc)
    add_config(p_qc)
    add_interval(p_qc)
    p_qc.set_defaults(func=cmd_qc)

    p_cal = sub.add_parser("calibrate", help="fit corrections from co-location data and apply them")
    p_cal.add_argument("--colocation", default=f"{DEFAULT_DATA}/colocation.jsonl")
    p_cal.add_argument(
        "--fit-only", action="store_true", help="fit and write registry, do not apply"
    )
    add_store(p_cal)
    p_cal.set_defaults(func=cmd_calibrate)

    p_agg = sub.add_parser("aggregate", help="build the gridded heat/AQI surface")
    p_agg.add_argument("--out", default="", help="GeoJSON output path")
    add_store(p_agg)
    add_config(p_agg)
    p_agg.set_defaults(func=cmd_aggregate)

    p_alerts = sub.add_parser(
        "alerts", help="build the neighborhood heat/AQI alerts feed (JSON + Atom)"
    )
    p_alerts.add_argument("--format", choices=("json", "atom", "none"), default="json")
    p_alerts.add_argument(
        "--web", default="", help="also bake alerts.json + alerts.xml into this web dir"
    )
    p_alerts.add_argument(
        "--base-url", default="http://localhost:8000", help="base URL for feed self/links"
    )
    add_store(p_alerts)
    add_config(p_alerts)
    p_alerts.set_defaults(func=cmd_alerts)

    p_exp = sub.add_parser("export", help="export observations as CSV or JSON to stdout")
    p_exp.add_argument("--format", choices=("csv", "json"), default="csv")
    p_exp.add_argument("--since", default=None)
    p_exp.add_argument("--until", default=None)
    p_exp.add_argument("--node", default=None)
    p_exp.add_argument("--parameter", default=None)
    p_exp.add_argument("--bbox", default=None, help="named area (reserved; see docs/api.md)")
    add_store(p_exp)
    add_interval(p_exp)
    p_exp.set_defaults(func=cmd_export)

    p_serve = sub.add_parser("serve", help="serve the dashboard, API, and exports (read-only)")
    p_serve.add_argument("--host", default="127.0.0.1")
    p_serve.add_argument("--port", type=int, default=8000)
    p_serve.add_argument("--web", default=DEFAULT_WEB)
    add_store(p_serve)
    add_config(p_serve)
    add_cooling(p_serve)
    p_serve.set_defaults(func=cmd_serve)

    p_iserve = sub.add_parser(
        "ingest-serve",
        help="run the authenticated node write path (write-only listener, per-node HMAC)",
    )
    p_iserve.add_argument("--host", default="127.0.0.1")
    p_iserve.add_argument("--port", type=int, default=8100)
    p_iserve.add_argument(
        "--keys", default=DEFAULT_KEYS, help="operator-local node-keys file (swelter node-key)"
    )
    p_iserve.add_argument(
        "--skew",
        type=float,
        default=ingest_server.DEFAULT_SKEW_S,
        help="replay window: max seconds between a request's signed timestamp and server time",
    )
    add_store(p_iserve)
    p_iserve.set_defaults(func=cmd_ingest_serve)

    p_key = sub.add_parser(
        "node-key", help="issue or rotate a node's ingest HMAC key (operator-local keys file)"
    )
    p_key.add_argument("node_id", help="the host-assigned node id the key authenticates")
    p_key.add_argument(
        "--keys", default=DEFAULT_KEYS, help="operator-local node-keys file to create/update"
    )
    p_key.set_defaults(func=cmd_node_key)

    p_demo = sub.add_parser("demo", help="replay recorded data through the whole pipeline")
    p_demo.add_argument("--data", default=DEFAULT_DATA)
    p_demo.add_argument("--store", default=f"{DEFAULT_STORE}/demo")
    p_demo.add_argument("--serve", action="store_true", help="serve the dashboard after replaying")
    p_demo.add_argument("--host", default="127.0.0.1")
    p_demo.add_argument("--port", type=int, default=8000)
    p_demo.add_argument("--web", default=DEFAULT_WEB)
    add_config(p_demo)
    add_interval(p_demo)
    add_cooling(p_demo)
    p_demo.set_defaults(func=cmd_demo)

    p_fetch = sub.add_parser(
        "fetch",
        help="fetch REAL readings from a live open-data source and build the dashboard",
    )
    p_fetch.add_argument(
        "--source",
        choices=("openmeteo", "openaq", "sensor-community"),
        default="openmeteo",
        help="openmeteo: Copernicus CAMS model data, California (keyless, coarse); "
        "openaq: dense real sensors, California, block-by-block (needs API key); "
        "sensor-community: real community low-cost sensors (dense in Europe)",
    )
    p_fetch.add_argument("--store", default=f"{DEFAULT_STORE}/real")
    p_fetch.add_argument("--config", default="network.real.yaml", help="where to write the network")
    p_fetch.add_argument("--web", default=DEFAULT_WEB)
    p_fetch.add_argument(
        "--accumulate",
        action="store_true",
        help="keep the existing store between runs instead of wiping it first, so history "
        "builds up across repeated fetches (e.g. daily CI) instead of one snapshot per run",
    )
    p_fetch.add_argument(
        "--past-days", type=int, default=2, help="openmeteo: history window (days)"
    )
    p_fetch.add_argument("--forecast-days", type=int, default=1)
    # openaq (real California sensors — block-by-block):
    p_fetch.add_argument("--api-key", default="", help="openaq: API key (or set OPENAQ_API_KEY)")
    p_fetch.add_argument("--max-locations", type=int, default=200, help="openaq: site cap")
    p_fetch.add_argument(
        "--throttle", type=float, default=1.1, help="openaq: seconds between calls"
    )
    # sensor-community area (defaults to Stuttgart, where coverage is dense):
    p_fetch.add_argument("--area-name", default="Stuttgart", help="sensor-community: area label")
    p_fetch.add_argument("--lat", type=float, default=48.7758, help="sensor-community: centre lat")
    p_fetch.add_argument("--lon", type=float, default=9.1829, help="sensor-community: centre lon")
    p_fetch.add_argument("--radius", type=float, default=30.0, help="sensor-community: radius km")
    p_fetch.add_argument("--serve", action="store_true", help="serve the dashboard after fetching")
    p_fetch.add_argument("--host", default="127.0.0.1")
    p_fetch.add_argument("--port", type=int, default=8000)
    add_interval(p_fetch)
    add_cooling(p_fetch)
    p_fetch.set_defaults(func=cmd_fetch)

    p_rebuild = sub.add_parser("rebuild", help="rebuild calibrated + surface from immutable raw")
    add_store(p_rebuild)
    add_config(p_rebuild)
    p_rebuild.set_defaults(func=cmd_rebuild)

    p_plan = sub.add_parser(
        "plan", help="siting what-if: coverage/redundancy/distance simulation for a candidate node"
    )
    p_plan.add_argument(
        "--add-node",
        required=True,
        metavar="lat,lon",
        help="candidate coordinate to simulate, e.g. --add-node 33.87,-117.92",
    )
    p_plan.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    add_config(p_plan)
    p_plan.set_defaults(func=cmd_plan)

    p_version = sub.add_parser("version", help="print the swelter version")
    p_version.set_defaults(func=cmd_version)

    p_cross = sub.add_parser(
        "crosswalk",
        help="print the outbound parameter crosswalk (swelter -> OpenAQ / Sensor.Community)",
    )
    p_cross.add_argument("--format", choices=("csv", "json"), default="csv")
    p_cross.set_defaults(func=cmd_crosswalk)

    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    func = args.func
    result: int = func(args)
    return result


if __name__ == "__main__":
    raise SystemExit(main())
